services:
  bank_db:
    container_name: bank_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bank_database
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network

  bank_api:
    container_name: bank_api
    build:
      context: .
    restart: always
    env_file:
      - .env.development
    ports:
      - 5007:3000
    depends_on:
      - bank_db
    networks:
      - app-network

volumes:
  pg-data:

networks:
  app-network:
    driver: bridge
